#!/usr/bin/env python3
"""Write ``association/query/duckdb_lower.py``: DuckDB's ``lower()`` as data.

    uv run python scripts/gen_duckdb_lower.py

``names.sql_lower`` has to lower a name exactly as DuckDB's ``lower()`` does,
and until 5.0.0's last change it leaned on ``str.lower()`` to do it - which
agrees with DuckDB only while the interpreter's Unicode tables are the
version DuckDB bundles. Measured 2026-10-02 against DuckDB 1.5.5: Python
3.12 and 3.13 agree on every code point, 3.10 (Unicode 13) and 3.14
(Unicode 16) do not. So the mapping is asked of DuckDB once, here, and
committed as a table no interpreter can move.

Run it after a DuckDB upgrade that fails
``tests/query/test_names.py::test_lowering_is_duckdbs_over_every_code_point``
- that test compares the committed table with the installed DuckDB over
every code point, so a stale table is a red suite, never a quiet drift.
"""

from __future__ import annotations

import pathlib
import sys

import duckdb

OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "association" / "query" / "duckdb_lower.py"

HEADER = '''"""DuckDB's ``lower()``, as data: every code point it maps to another one.

GENERATED by ``scripts/gen_duckdb_lower.py`` from DuckDB {version} - do not
edit; run the script again after a DuckDB upgrade. {mapped:,} code points in
{runs} runs, each ``(first, last, delta, step)``: every ``step``-th code point
from ``first`` to ``last`` lowers to itself plus ``delta``. A table rather
than ``str.lower()`` because Python's mapping follows the interpreter's
Unicode version and DuckDB's follows its own (:func:`association.query.names.sql_lower`).

.. versionadded:: 5.0.0
"""

from __future__ import annotations

LOWER_RUNS: tuple[tuple[int, int, int, int], ...] = (
'''

FOOTER = ''')
"""The runs, in code point order.

.. versionadded:: 5.0.0
"""
'''


def mapping() -> dict[int, int]:
    """Each code point DuckDB's ``lower()`` changes, with what it becomes."""
    every = [chr(code) for code in range(1, 0x110000) if not 0xD800 <= code <= 0xDFFF]
    rows = duckdb.connect().execute("SELECT c, lower(c) FROM (SELECT unnest(?) AS c)", [every]).fetchall()
    changed = {ord(char): lowered for char, lowered in rows if char != lowered}
    long = [hex(code) for code, lowered in changed.items() if len(lowered) != 1]
    if long:
        raise SystemExit(f"DuckDB lowers {long} to more than one code point: the run table cannot hold that")
    return {code: ord(lowered) for code, lowered in changed.items()}


def runs(changed: dict[int, int]) -> list[tuple[int, int, int, int]]:
    """``changed`` as the fewest ``(first, last, delta, step)`` runs, in code
    point order: neighbors one or two apart that move by the same amount."""
    found: list[list[int]] = []
    for code in sorted(changed):
        delta = changed[code] - code
        last = found[-1] if found else None
        if last is not None and last[2] == delta and code - last[1] in (1, 2) and last[3] in (0, code - last[1]):
            last[1], last[3] = code, code - last[1]
        else:
            found.append([code, code, delta, 0])
    return [(first, last, delta, step or 1) for first, last, delta, step in found]


def main() -> int:
    """Ask DuckDB and write the module."""
    changed = mapping()
    table = runs(changed)
    rebuilt = {code: code + delta for first, last, delta, step in table for code in range(first, last + 1, step)}
    if rebuilt != changed:
        raise SystemExit("the runs do not rebuild DuckDB's mapping: a bug in runs()")
    body = "".join(f"    (0x{first:04X}, 0x{last:04X}, {delta}, {step}),\n" for first, last, delta, step in table)
    OUT.write_text(HEADER.format(version=duckdb.__version__, mapped=len(changed), runs=len(table)) + body + FOOTER)
    print(f"wrote {OUT}: {len(changed):,} code points in {len(table)} runs, from DuckDB {duckdb.__version__}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
